//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextsRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextsRU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Console.Resources.TextsRU", typeof(TextsRU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атакуйте корабли противника. \n Передвигать прицел - WASD или Стрелки.\n Атакавать ячейку - Enter..
        /// </summary>
        internal static string AttackEnemyTask {
            get {
                return ResourceManager.GetString("AttackEnemyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра закончена.\n - Начать заново - R\n Выйти из игры - Q.
        /// </summary>
        internal static string EndGamePromt {
            get {
                return ResourceManager.GetString("EndGamePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ░▒▓███████▓▒░▒▓████████▓▒░░▒▓██████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░▒▓████████▓▒░▒▓█▓▒░      ░▒▓████████▓▒░ \r\n░▒▓█▓▒░      ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░      ░▒▓█▓▒░   ░▒▓█▓▒░      ░▒▓█▓▒░        \r\n░▒▓█▓▒░      ░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░      ░▒▓█▓▒░   ░▒▓█▓▒░      ░▒▓█▓▒░        \r\n ░▒▓██████▓▒░░▒▓██████▓▒░ ░▒▓████████▓▒░      ░▒▓███████▓▒░░▒▓████████▓▒░ ░▒▓█▓▒░      ░▒▓█▓▒░   ░▒▓█▓▒░      ░▒▓██████▓▒░   \ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О боже, вы проиграли глупому компьютеру как так..
        /// </summary>
        internal static string LosePromt {
            get {
                return ResourceManager.GetString("LosePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расставьте корабли на игровом поле.\n- Двигать корабль - WASD или Стрелки.\n- Поставить корабль - Enter.\n- Повернуть R..
        /// </summary>
        internal static string PlaceShipsTask {
            get {
                return ResourceManager.GetString("PlaceShipsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите любую кнопку чтобы начать. . ..
        /// </summary>
        internal static string StartPromt {
            get {
                return ResourceManager.GetString("StartPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___       ________  ________  _______      
        ///|\  \     |\   __  \|\   ____\|\  ___ \     
        ///\ \  \    \ \  \|\  \ \  \___|\ \   __/|    
        /// \ \  \    \ \  \\\  \ \_____  \ \  \_|/__  
        ///  \ \  \____\ \  \\\  \|____|\  \ \  \_|\ \ 
        ///   \ \_______\ \_______\____\_\  \ \_______\
        ///    \|_______|\|_______|\_________\|_______|
        ///                       \|_________|.
        /// </summary>
        internal static string WinEnemyLabel {
            get {
                return ResourceManager.GetString("WinEnemyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _______     _______     ____________  _____    _____     
        ///  /      /|   |\      \   /            \|\    \   \    \    
        /// /      / |   | \      \ |\___/\  \\___/|\\    \   |    |   
        ///|      /  |___|  \      | \|____\  \___|/ \\    \  |    |   
        ///|      |  |   |  |      |       |  |       \|    \ |    |   
        ///|       \ \   / /       |  __  /   / __     |     \|    |   
        ///|      |\\/   \//|      | /  \/   /_/  |   /     /\      \  
        ///|\_____\|\_____/|/_____/||____________/|  /_____/ /______/| 
        ///| |     | |   | |   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WinPlayerLabel {
            get {
                return ResourceManager.GetString("WinPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляю вы победили..
        /// </summary>
        internal static string WinPromt {
            get {
                return ResourceManager.GetString("WinPromt", resourceCulture);
            }
        }
    }
}
